version: "3.9"
services:
  mysql:
    container_name: base_sf_6_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    
  adminer:
    container_name: base_sf_6_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
  mailhog:
    container_name: base_sf_6_mailhog
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
        
  php:
    container_name: base_sf_6_php
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mailhog
    environment:
      - DATABASE_URL=${DATABASE_URL}
      
  caddy:
    container_name: base_sf_6_caddy
    image: caddy:2.6.2-alpine
    depends_on:
      - php
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/var/www/html/public
      - ./var/log/caddy:/var/log/caddy

volumes:
  caddy_data:
  caddy_config:
